basePath: /
definitions:
  proxy.ProxyRequest:
    properties:
      headers:
        additionalProperties:
          type: string
        type: object
      method:
        type: string
      url:
        type: string
    type: object
  proxy.ProxyResponse:
    properties:
      headers:
        additionalProperties:
          type: string
        type: object
      id:
        type: string
      length:
        type: integer
      status:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a proxy server API.
  title: Proxy Server API
  version: "1.0"
paths:
  /health:
    get:
      description: Returns the health status of the server
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health check
  /proxy:
    post:
      consumes:
      - application/json
      description: Proxies a request to the specified URL and returns the response
      parameters:
      - description: Proxy Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/proxy.ProxyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/proxy.ProxyResponse'
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Proxy a request
swagger: "2.0"
